### ISSUE TITLE
Null reference exception

### ISSUE THREAD

**Issue by vadim3004** [r-Larch/TcBuild#1]
Is this project alive? 
I've got an exception 

03/27/20 20:09:22.458  - Warn  - IContentPlugin plugin load: [A1|T1] [TCSharp]TCSharp.Scriptor
'TOTALCMD64.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'TOTALCMD64.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
03/27/20 20:09:22.473  - Error - NULL: [A1|T1] SetDefaultParams: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at TcPluginBase.Tools.TcPluginLoader.CreatePluginInstance[TPlugin](Type pluginClass)
   at TcPluginBase.Tools.TcPluginLoader.GetTcPlugin[TPlugin](Type pluginClass)
   at WdxWrapper.ContentWrapper.get_Plugin()
   at WdxWrapper.ContentWrapper.SetDefaultParams(PluginDefaultParams& defParams)

**Comment by r-Larch** [comment]
Hi @vadim3004,

sorry for my late response, notifications were turned off for this Project.

The Content Plugin was never fully implemented before I set this project on hold, 
while I was waiting for .NET Core support for Source Generators and native DllExports.
Because my plans are migrating this to .NET Core as soon as it has all features required for this project.

Now it seems like it would be possible to migrate to .NET 5 because it can achieve native DllExports by using the DNNE Nuget, but official support gets possibly added in .NET 6.

So maybe I migrate to .NET 5 or I wait for .NET 6, this depends on how much free time I can invest in this project.

After migration, I will finalize all plugin implementations and provide an example for each as seen with the FileSystem Plugin.
